name: Coq build
on:
  push: 
    branches: [ main ]
    paths: [ coq/** ]
  pull_request:
    branches: [ main ]
    paths: [ coq/** ]
jobs:
  build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        coq_version:
          - dev
        ocaml_version: ['default']
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq/coq-iris-exercises.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
